### ISSUE TITLE
Clustering der Knoten auf Knopfdruck deaktivieren

### ISSUE THREAD

**Issue by nazco** [Freifunk-Rhein-Neckar/website#13]
Ich würde mir ein Feature wünschen, mit dem ich auf Knopfdruck (Knopf unter oder über den existierenden +/- Steuerelementen) das Clustering der Knoten deaktivieren kann und so alle Knoten mit ihrer eingetragenen Position sehe.

**Comment by lukasbisdorf** [comment]
Kann man relativ leicht einbauen. 

Memo an mich selbst:

```javascript
var setSizeTo = function (size) {
// -1 für mit ohne cluster. 
    pruneCluster.Cluster.Size = size;
    pruneCluster.ProcessView();
  }
```

**Comment by lukasbisdorf** [comment]
Der gewählte status sollte auch persistent gemacht werden, so dass der Benutzer seine Vorliebe nicht bei jedem Besuch neu wählen muss.

**Comment by lukasbisdorf** [comment]
Eingebaut.
