### ISSUE TITLE
More content for start page

### ISSUE THREAD

**Issue by silsha** [Freifunk-Rhein-Neckar/website#2]

**Comment by inf1832** [comment]
Ich hab hier eine Idee, und schon mal was in JS gebastelt. Bekomm mit den Dev tools ungefähr so hin, wie es mal aussehen soll. Aber so richtig funktioniert das CSS nicht.
Könnte das vielleicht jemand irgendwie so hinbasteln dass es so aussieht und funktioniert? 

![image](https://cloud.githubusercontent.com/assets/1409857/5854019/9739b1da-a229-11e4-9e09-e15fcb9fbe7c.png)


Ziel war es, die Karte in den Hintergrund zu stellen, so dass sie von den anderen container überlagert wird. 

Der Footer soll in jedem fall auf Computern zu sehen sein, weil man auf der Karte schlecht scrollen kann (Die zoomt dann). Daher soll die Karte den Platz vom oberen Bildschirmrand minus den Platz vom Footer einnehmen. 

Für das Menü stell ich mir einen weißen/grauen Backgrund mit Blur vor, so dass man sieht dass sich die Karte hinter das Menü schiebt und einen weichen Übergang bildet. 

Was man mit mobile macht ¯\_(ツ)_/¯ - sollten wir mal noch drüber quatschen. 

Das JS von der Karte ist bisher auch noch ein bisschen experimentell. Geplant ist noch
  - Knotennamen einblenden
  - bessere Icons für die Knoten
  - Onlinestatus abhängige Farben der node marker
  - "Live Aktualisierung" mit polling
  - Popup on hover oder Klick mit Detailinformationen zu dem knoten
  - Gesamtzahlen irgendwo mit einbinden. 

Das ganze befindet sich im Branch "liveStats". Wegen der Abhängigkeit von der proxy.php sollte das ganze in ner php Umgebung getestet werden.

**Comment by lukasbisdorf** [comment]
Geplante features sind jetzt soweit implementiert.

liveStats kann dann mal in den master.
