### ISSUE TITLE
Statistik Daten laufen über

### ISSUE THREAD

**Issue by nazco** [Freifunk-Rhein-Neckar/website#32]
Die Daten aus der Statistik wrappen in ne zweite Zeile. Das sollten wir irgendwie fixen.
![screenshot2016-02-23_16-36-43](https://cloud.githubusercontent.com/assets/1292551/13256618/b2804ac0-da4b-11e5-92b0-90b28b21eee8.png)

**Comment by lukasbisdorf** [comment]
Das läuft nicht über. Das ist Responsive. :smile: 

----

Das Problem ist, dass dein Browser einfach ein bisschen schmal für so viele Daten ist. Wir könnten die Prozent Zahlen ausblenden, wenn der Browser zu klein ist. 
Aber ich finde es bricht ganz gut um. Vielleicht schafft man es ja auch, das per css so zu fummeln, dass immer der ganze Block, ab dem Icon umbricht.

**Comment by lukasbisdorf** [comment]
Funktioniert wie es soll.
