### ISSUE TITLE
Missing node information on front page

### ISSUE THREAD

**Issue by Nurtic-Vibe** [Freifunk-Rhein-Neckar/website#38]
Currently there is an issue that node names on the front page are missing when clicking on a single node.
Screenshot: [https://cloud.grmml.eu/s/Nnzfatz62FfzujB](url)
In some cases there might also be the issue, that the node itself is not clickable at all ( @nazco reported this issue in Chat)

**Comment by lukasbisdorf** [comment]
Fixed by #40
