### ISSUE TITLE
Small margin on the right of the LiveStats

### ISSUE THREAD

**Issue by lukasbisdorf** [Freifunk-Rhein-Neckar/website#8]
Small margin on the right of the LiveStats

**Comment by lukasbisdorf** [comment]
Fixed on Mac with commit fe12cb9d555af478844296147d36766afa9859ad

Breaks on Windows with FF an IE

**Comment by nazco** [comment]
also broken on chromium

**Comment by lukasbisdorf** [comment]
fixed.
